# site settings
title: SAIR Lab
subtitle: Social AI & Robotics
email: sairlteam@gmail.com
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: 
street_address: Department of Engineering
city: King's College London 
state: Strand London
zip_code: WC2R 2LS
country: United Kingdom
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sairlab
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/SAIRLab

# build settings
markdown: kramdown

sass:
  style: compressed
